# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

###
# Variable Declaration and Initalization
###
termcol="$(tput colors)"
source /usr/share/zinit/zinit.zsh
export PF_INFO="ascii title os host kernel wm editor shell uptime pkgs memory"
export EDITOR='emacsclient -t'
export VISUAL='emacsclient -c'

###
# Zplug initalization
###

### Add Plugins
zinit ice depth"1"
zinit light "romkatv/powerlevel10k"
zinit light "jeffreytse/zsh-vi-mode"
zinit snippet OMZ::plugins/sudo/sudo.plugin.zsh
zinit light "zsh-users/zsh-syntax-highlighting"
zinit light "zsh-users/zsh-history-substring-search"
zinit light "marlonrichert/zsh-autocomplete"
zinit light "zsh-users/zsh-autosuggestions"
zinit light "zsh-users/zsh-completions"
zinit ice svn
zinit snippet OMZ::plugins/emacs

clear
pfetch

####
# User Configurations
####

HISTFILE=~/.config/zsh/.zsh_history
HISTSIZE=1000
SAVEHIST=1000

# Alias
alias doom=${XDG_CONFIG_HOME:-$HOME/.config}/emacs/bin/doom
alias org-tangle='${XDG_CONFIG_HOME:-$HOME/.config}/emacs/bin/org-tangle ${XDG_CONFIG_HOME:-$HOME/.config}/doom/config.org'

#Enable AutoCD into dir, terminal bell, and terminal notify
setopt autocd beep notify

# Enable Vi mode
bindkey -v

# History scroll
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down
bindkey -M vicmd 'k' history-substring-search-up
bindkey -M vicmd 'j' history-substring-search-down

# To customize prompt, run `p10k configure` or edit ~/.config/zsh/.p10k.zsh.
if [ $termcol != 256 ] ; then
  [[ ! -f /etc/skel/.p10k_min.zsh ]] || source /etc/skel/.p10k_min.zsh
else
  [[ ! -f ~/.config/zsh/.p10k.zsh ]] || source ~/.config/zsh/.p10k.zsh
fi

# FZF Initalization
source /usr/share/fzf/key-bindings.zsh
source /usr/share/fzf/completion.zsh

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
